---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'

  roles:
    - role: nephelaiio.unifi-controller
    - role: ccunix.unifi_expoter

  post_tasks:
    - name: Ensure unifi_exporter is running
      uri:
        url: http://127.0.0.1:9311/metrics
        status_code: 200
      register: result
      until: result.status == 200
      retries: 60
      delay: 1
