name: Static code analysis
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ansible-later:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ansible-later
        uses: patrickjahns/ansible-later-action@v1
        with:
          config: ".later.yml"
          path: "**/*.yml"
